# Generated by Django 4.1.2 on 2022-10-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
